parameters:
    cache_tags.command.invalidate_tag.class: lbarulski\CacheTagsBundle\Command\InvalidateTagCommand

services:
    cache_tags.command.invalidate_tag:
        class:      "%cache_tags.command.invalidate_tag.class%"
        arguments:  ["@cache_tags.invalidator"]
        tags:
            - { name: console.command }
